### ISSUE TITLE
French fries image not showing.

### ISSUE THREAD

**Issue by samarmohan** [aashishpeepra/RestaurantReactApp#3]
When I go to the menu to order something and select Appetizers, the first item's - which is a fry - image doesn't show up. There is an alternate which says "Maccain"

**Comment by aashishpeepra** [comment]
@samarmohan  The images aren't stored in the backend. Instead of that the image url of each image is stored in the [Firebase Realtime Database](https://firebase.google.com/docs/database) 

At the time of creation of the database (more than 2 years back) the image url was valid. Maybe the url got removed. 

The issue is the fault url in the database. 

when someone use their own schema they can insert correct urls and it will start working.

**Comment by samarmohan** [comment]
I pointed this out because the app is in production. You should either have the full app in production or make the other developers do everything, it shouldn't be both ways.
