### ISSUE TITLE
Google Maps says "For development purposes only"

### ISSUE THREAD

**Issue by samarmohan** [aashishpeepra/RestaurantReactApp#4]
On the home page at the bottom: The Google Map is dark, has a grid layout, says "For development purposes only", asks if you own the site, and finally says this "This page can't load Google Maps correctly".
This makes the UX very poor.

**Comment by aashishpeepra** [comment]
Hey 👋 @samarmohan 

The google map issue is because I don't have API keys to access the geolocation services by google. Therefore I left the API keys insertion place empty so whosoever wants to use the map can simply slip their keys in it.

This isn't an issue just a template-ing method. Therefore I'm closing it.
